apiVersion: v1
kind: Service
metadata:
  name: yolov5-detection-service
spec:
  selector:
    app: yolov5-detection
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30001
